### ISSUE TITLE
Latest Image doesn't seem to have odo installed

### ISSUE THREAD

**Issue by wkulhanek** [openshift-homeroom/workshop-terminal#26]
All odo's in /usr/local/bin are just 9 bytes long and contain "Not Found".

**Comment by GrahamDumpleton** [comment]
Looks like the odo repository was moved/renamed/shifted between organisations multiple times and broke any sensible redirections that GitHub was doing to ensure you ended up at the correct place.

**Comment by GrahamDumpleton** [comment]
Should be fix in version 3.1.0 of terminal base image. Still need to update derived dashboard image.

**Comment by GrahamDumpleton** [comment]
The dashboard image version is 4.2.0.
