### ISSUE TITLE
Terminal Not Loading on 4.2 Cluster

### ISSUE THREAD

**Issue by danielhelfand** [openshift-homeroom/workshop-terminal#27]
Was going through the Tekton workshop and noticed the terminals aren't loading for the workshop as show below:

![image](https://user-images.githubusercontent.com/34258252/68030712-7b8f7480-fc90-11e9-9d44-f041cb1558f3.png)

Commands aren't executing and nothing can be typed. 

Noticed updates here recently so wanted to see if the changes were related.

**Comment by GrahamDumpleton** [comment]
Did you try the 'Reload Terminals' menu option. This just happens sometimes, especially if got bad internet connection. Worse case just reload the whole browser version.

**Comment by danielhelfand** [comment]
Reloading/refreshing session doesn't appear to resolve it, but I am beginning to suspect it may be an issue with the cluster itself. Let me look at it with a fresh one and see if this continues.

**Comment by danielhelfand** [comment]
Appears to work fine with a new cluster. Must have been something with the cluster itself.
